"""tempest-core — the renderer-agnostic core shared across the tempest stack.

The engine behind both tempestroid (native renderers) and tempestweb (DOM): the
IR, reconciler, state model, style model, widgets, components and the
cross-cutting helpers (animation, i18n, navigation, theme, validators). It carries
no platform-coupled code (no Qt, no JNI, no Android, no DOM) so it imports cleanly
under CPython, Pyodide and a headless server.

This is the single source of truth — consumers depend on the published package and
import from here (``from tempest_core import App, Column, build, diff``) rather than
vendoring a copy.
"""

from tempest_core.animation import AnimationController
from tempest_core.components import (
    Alert,
    Badge,
    Banner,
    BarChart,
    ChartSeries,
    Chip,
    ConfidenceBadge,
    DetectionBox,
    DetectionOverlay,
    EmptyState,
    HStack,
    LineChart,
    MetricCard,
    ProgressStepper,
    ResultView,
    Stat,
    StatCard,
    StyledContainer,
    Surface,
    Tabs,
    Tag,
    VStack,
    confidence_scheme,
)
from tempest_core.core import (
    App,
    Insert,
    Node,
    OverlayEntry,
    Patch,
    Path,
    Remove,
    Reorder,
    Replace,
    Scene,
    Update,
    build,
    build_scene,
    diff,
    diff_scene,
    event_catalog,
    introspect,
    widget_catalog,
)
from tempest_core.i18n import Locale, t, translate
from tempest_core.navigation import NavStack, Route, routes_from_path
from tempest_core.style import (
    AlertVariant,
    BadgeVariant,
    CardVariant,
    ComponentState,
    FieldVariant,
    Size,
    Style,
    Variant,
)
from tempest_core.theme import MediaQueryData, Theme, ThemeMode
from tempest_core.tokens import (
    Breakpoints,
    ColorRole,
    ColorScheme,
    ColorSchemes,
    ElevationScale,
    MotionScale,
    ShapeScale,
    SpacingScale,
    TokenRef,
    TokenSet,
    TonalPalette,
    TypographyScale,
    TypographyToken,
    color_schemes_from_seed,
    default_tokens,
    tonal_palette_from_seed,
)
from tempest_core.variants import (
    BADGE_DENSITY,
    SELECTION_SIZE,
    SLIDER_SIZE,
    ResponsiveSize,
    resolve_alert_variant,
    resolve_badge_variant,
    resolve_badge_variant_states,
    resolve_field_variant,
    resolve_field_variant_states,
    resolve_selection_variant,
    resolve_selection_variant_states,
    resolve_size,
    resolve_slider_variant,
    resolve_slider_variant_states,
    resolve_surface_variant,
    resolve_variant,
    resolve_variant_states,
)
from tempest_core.widgets import (
    Button,
    Column,
    Component,
    Container,
    IconButton,
    Row,
    Spacer,
    Text,
    Widget,
)

__all__ = [
    "Alert",
    "AlertVariant",
    "AnimationController",
    "App",
    "BADGE_DENSITY",
    "Badge",
    "BadgeVariant",
    "Banner",
    "BarChart",
    "Breakpoints",
    "Button",
    "CardVariant",
    "ChartSeries",
    "Chip",
    "ConfidenceBadge",
    "Column",
    "ColorRole",
    "ColorScheme",
    "ColorSchemes",
    "Component",
    "ComponentState",
    "Container",
    "DetectionBox",
    "DetectionOverlay",
    "ElevationScale",
    "EmptyState",
    "FieldVariant",
    "HStack",
    "IconButton",
    "Insert",
    "LineChart",
    "Locale",
    "MediaQueryData",
    "MetricCard",
    "MotionScale",
    "NavStack",
    "Node",
    "OverlayEntry",
    "Patch",
    "Path",
    "ProgressStepper",
    "Remove",
    "Reorder",
    "Replace",
    "ResponsiveSize",
    "ResultView",
    "Route",
    "Row",
    "SELECTION_SIZE",
    "SLIDER_SIZE",
    "Scene",
    "ShapeScale",
    "Size",
    "Spacer",
    "SpacingScale",
    "Stat",
    "StatCard",
    "Style",
    "StyledContainer",
    "Surface",
    "Tabs",
    "Tag",
    "Text",
    "Theme",
    "ThemeMode",
    "VStack",
    "TokenRef",
    "TokenSet",
    "TonalPalette",
    "TypographyScale",
    "TypographyToken",
    "Update",
    "Variant",
    "Widget",
    "build",
    "build_scene",
    "color_schemes_from_seed",
    "confidence_scheme",
    "default_tokens",
    "diff",
    "diff_scene",
    "event_catalog",
    "introspect",
    "resolve_alert_variant",
    "resolve_badge_variant",
    "resolve_badge_variant_states",
    "resolve_field_variant",
    "resolve_field_variant_states",
    "resolve_selection_variant",
    "resolve_selection_variant_states",
    "resolve_size",
    "resolve_slider_variant",
    "resolve_slider_variant_states",
    "resolve_surface_variant",
    "resolve_variant",
    "resolve_variant_states",
    "routes_from_path",
    "t",
    "tonal_palette_from_seed",
    "translate",
    "widget_catalog",
]
